project:
  type: website
  output-dir: docs

website:
  favicon: images/eric-pro.jpg
  title: "Data Scientist & Machine Learning Engineer"
  google-analytics: "G-KXW8KRW3V1"
  navbar:
    background: primary
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Projects
      - href: contact.qmd
        text: Contacts
      - href: event.qmd
        text: Events

    rigth:
      - icon: github
        href: https://github.com/dona-eric
      - icon: Linkedin
        href : https://www.linkedin.com/in/dona-erick
      - icon : Twitter
        href : https://x.com/Ericschrodinger
      - icon : Facebook
        href : https://www.facebook.com/eric.koulodji
      - icon : Medium
        href : https://www.medium.com/@koulodjiric

  sidebar:
    style: "docked"
    search: true

  page-footer:
    left:
      © 2025 Eric KOULODJI - Data Scientist & ML Engineer
    center:
      Créé avec [Quarto](https://quarto.org)
    right:
      [🇧🇯 Abomey-Calavi, Bénin]
format:
  html:
    theme: 
      light: [cosmo, styles.css]
      dark: [slate, styles.css]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    highlight-style: github
    code-fold: true
    code-tools: true
    smooth-scroll: true
      
execute:
  freeze: auto



